In [1]:
import numpy as np
#from numpy import * #将numpy中的模块 函数等 全部释放出来 调用的时候 就不需要np.*了 直接使用名字即可 e.g.:dot(a,b)

In [2]:
a=np.matrix(np.random.rand(4,4))
b=a.I

In [3]:
a

matrix([[ 0.37696883,  0.27440436,  0.60067494,  0.33078543],
        [ 0.94160512,  0.58562423,  0.09218194,  0.10135778],
        [ 0.05064061,  0.21515189,  0.35730728,  0.70876357],
        [ 0.75996135,  0.69859942,  0.80124981,  0.38928902]])

In [5]:
a*b#矩阵乘法

matrix([[  1.00000000e+00,  -4.16333634e-17,  -1.11022302e-16,
           1.11022302e-16],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
           4.44089210e-16],
        [  0.00000000e+00,   5.55111512e-17,   1.00000000e+00,
           1.08420217e-18],
        [  0.00000000e+00,  -1.11022302e-16,   0.00000000e+00,
           1.00000000e+00]])

In [8]:
np.multiply(a,b)#哈达玛积

matrix([[ 1.54441494,  0.52848082, -0.30137944, -1.01524207],
        [-6.6209111 , -0.79957918,  0.060475  ,  0.52055946],
        [ 0.09054454, -0.21962376, -0.33232052,  0.31174271],
        [ 0.71465936,  0.55291609,  1.37533158, -0.60786853]])

In [9]:
np.matmul(a,b)#矩阵乘法
np.dot(a,b)#矩阵乘法

matrix([[  1.00000000e+00,  -4.16333634e-17,  -1.11022302e-16,
           1.11022302e-16],
        [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
           4.44089210e-16],
        [  0.00000000e+00,   5.55111512e-17,   1.00000000e+00,
           1.08420217e-18],
        [  0.00000000e+00,  -1.11022302e-16,   0.00000000e+00,
           1.00000000e+00]])

In [10]:
np.eye(8)#单位矩阵

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])