In [1]:
#====
#线性回归 最小二乘法
from sklearn import linear_model


In [4]:
reg = linear_model.LinearRegression()
reg.fit([[0,0],[1,1],[2,2]] , [0,1,2])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
print(reg.coef_ ,  reg.intercept_)

[0.5 0.5] 2.220446049250313e-16


In [6]:
reg.predict([3,3])

I:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([3.])

In [ ]:
#===
#岭回归
reg = linear_model.Ridge()

reg.coef_() #权重
reg.intercept_() #偏置

In [8]:
reg = linear_model.RidgeCV(alphas=[0.1 , 1.0 , 10.0])
#alphas参数是为了交叉验证而选择的惩罚项 正则化参数
reg.fit([[0,0],[0,0],[1,1]] , [0,0.1,1])



RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [9]:
reg.alpha_

0.1

In [ ]:
#===
#lasso 回归
#因此，Lasso及其变体是压缩感知领域的基础。
#l1可以用来特征选择
reg = linear_model.Lasso(alpha=0.1)
reg.fit()

In [ ]:
reg = linear_model.LassoCV
reg = linear_model.LassoLarsCV

In [ ]:
#===
#multi-task lasso

reg = linear_model.MultiTaskLasso()

In [ ]:
#===
#elastic net
#同时兼顾lasso和ridge 即权重的1范数和2范数
reg = linear_model.ElasticNet()
reg = linear_model.ElasticNetCV()

In [ ]:
#===
#multi task elastic net
reg = linear_model.MultiTaskElasticNet()

In [ ]:
#===
#lasso with LARS algorithm
reg = linear_model.LassoLars(alpha=0.1)
reg.conf_

In [ ]:
#===
#贝叶斯ridge回归
reg = linear_model.BayesianRidge()
reg.fit()

reg.coef_

In [ ]:
#===
#automatic relevance determination (ARD)
reg = linear_model.ARDRegression()
reg.fit()

In [ ]:
#===
#logistic regression
reg = linear_model.LogisticRegression()
#solver参数 是训练使用的训练器 就是不同的训练算法
#L1 LR 也可以进行特征选择（因为具有稀疏性）
#multi_class参数用来选择如何进行多分类
#ovr简单进行多分类 multinomial 真正对分类 交叉熵
reg = linear_model.SGDClassifier()

In [ ]:
#===
#SGD
reg = linear_model.SGDClassifier()

reg = linear_model.SGDRegressor()

In [ ]:
#===
#perceptron 感知机
reg = linear_model.Perceptron()

In [ ]:
#===
#passive aggressive algorithm
reg = linear_model.passive_aggressive()

In [ ]:
#===
#robustness regression
#离群值后者模型错误时

#RANSAC(random sample consensus)
reg = linear_model.RANSACRegressor()

In [ ]:
#===
#theilsenregressor
reg = linear_model.TheilSenRegressor()

In [ ]:
#===
#huberregressor
reg = linear_model.HuberRegressor()

In [10]:
#===
#===
#polynomial regression
#多项式回归
#先进行数据转换
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arange(6).reshape(3 , 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
poly = PolynomialFeatures(degree=2) #即将数据进行结合
poly.fit_transform(X)

#[x1,x2]=>[1,x1,x2,x1**2,x1x2,x2**2]

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [14]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])
x = np.arange(5)
y = 3-2*x+x**2-x**3

model = model.fit(x[: , np.newaxis] , y)
model.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])

In [15]:
np.newaxis

In [18]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = X[: ,0]^X[:, 1]
y

array([0, 1, 1, 0], dtype=int32)

In [19]:
X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)
X

array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [22]:
clf = Perceptron(fit_intercept=False ,shuffle=False).fit(X , y)

In [23]:
clf.predict(X)

array([1, 1, 1, 0], dtype=int32)

In [24]:
clf.score(X , y)

0.75