In [37]:
import tensorflow as tf
import numpy as np

In [13]:
a = tf.Variable([[[1,2]],[[12,2]],[[123,23]]])
b = tf.transpose(a , [1,0,2])
c = tf.unstack(a)

In [15]:
print(a)
print(b)
print(c)

<tf.Variable 'Variable_3:0' shape=(3, 1, 2) dtype=int32_ref>
Tensor("transpose_2:0", shape=(1, 3, 2), dtype=int32)
[<tf.Tensor 'unstack:0' shape=(1, 2) dtype=int32>, <tf.Tensor 'unstack:1' shape=(1, 2) dtype=int32>, <tf.Tensor 'unstack:2' shape=(1, 2) dtype=int32>]


In [19]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    
    print(sess.run(c[0]))
    

[[[  1   2]]

 [[ 12   2]]

 [[123  23]]]
[[[  1   2]
  [ 12   2]
  [123  23]]]
[[1 2]]


In [18]:
type(c)
c


[<tf.Tensor 'unstack:0' shape=(1, 2) dtype=int32>,
 <tf.Tensor 'unstack:1' shape=(1, 2) dtype=int32>,
 <tf.Tensor 'unstack:2' shape=(1, 2) dtype=int32>]

In [11]:
isinstance(a , tf.tensor)

AttributeError: module 'tensorflow' has no attribute 'tensor'

In [50]:
a = tf.Variable(np.random.randint(1,10,size=12))
a=tf.reshape(a , shape=[2,3,2])

In [62]:
mean , variance = tf.nn.moments(a , [0])


In [66]:
mean1 , var1 = tf.nn.moments(mean , [0])

In [47]:
print(a)

Tensor("Reshape:0", shape=(5, 4, 3, 2), dtype=int32)


In [67]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run([mean , variance]))
    print('===')
    print(sess.run([mean1 , var1]))

[[[2 8]
  [9 2]
  [9 4]]

 [[7 7]
  [7 2]
  [1 8]]]
[array([[4, 7],
       [8, 2],
       [5, 6]]), array([[ 6,  0],
       [ 1,  0],
       [16,  4]])]
===
[array([5, 5]), array([3, 4])]


In [32]:
img = tf.Variable(tf.random_normal([128, 32, 32, 64]))
axis = list(range(len(img.get_shape()) - 1))
print(axis)

[0, 1, 2]


In [43]:
a = np.random.randint(1,10 , size = 15)

array([8, 6, 2, 4, 4, 5, 3, 6, 7, 5, 5, 9, 8, 7, 9])