In [8]:
import tensorflow as tf
import numpy as np

In [17]:
#将神经网络保存起来 下次可以继续使用 或者继续训练

#=============
#保存起来
W = tf.Variable([[1,2,3] , [4,5,6]] , dtype = tf.float32 , name = 'weights')
b = tf.Variable([[1,2,3]] , dtype = tf.float32 , name = 'biases')

saver = tf.train.Saver()

sess = tf.Session()
sess.run(tf.global_variables_initializer())

save_path = saver.save(sess , 'check_point/save_test.ckpt')

print(save_path)

sess.close()

sess = tf.Session()
saver.restore(sess , 'check_point/save_test.ckpt')

print(sess.run(W))
print(sess.run(b))
sess.close()

check_point/save_test.ckpt
INFO:tensorflow:Restoring parameters from check_point/save_test.ckpt
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 1.  2.  3.]]


In [16]:
#===============
#恢复回来
#恢复的时候 shape dtype必须一样
#W_restore = tf.Variable(tf.zeros([2,3]) , dtype=tf.float32)
#b_restore = tf.Variable(tf.zeros([1,1]) , dtype=tf.float32)

W_restore = tf.Variable(np.arange(6).reshape((2,3)) , dtype = tf.float32 , name = 'weights')
b_restore = tf.Variable(np.arange(3).reshape((1,3)) , dtype = tf.float32 , name = 'biases')

#不需要sess.run(tf.global_variables_initializer())
#restore自动完成
ssaver = tf.train.Saver()

sess = tf.Session()
ssaver.restore(sess , "check_point/save_test.ckpt")

#print(sess.run(W_restore))
#print(sess.run(b_restore))

sess.close()

INFO:tensorflow:Restoring parameters from check_point/save_test.ckpt


NotFoundError: Key biases_10 not found in checkpoint
	 [[Node: save_12/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_12/Const_0_0, save_12/RestoreV2_4/tensor_names, save_12/RestoreV2_4/shape_and_slices)]]

Caused by op 'save_12/RestoreV2_4', defined at:
  File "I:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "I:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "I:\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "I:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "I:\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "I:\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "I:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "I:\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "I:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "I:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "I:\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "I:\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "I:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "I:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "I:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "I:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "I:\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "I:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "I:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "I:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-764c6691b9a8>", line 12, in <module>
    ssaver = tf.train.Saver()
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1140, in __init__
    self.build()
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 688, in build
    restore_sequentially, reshape)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "I:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key biases_10 not found in checkpoint
	 [[Node: save_12/RestoreV2_4 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_12/Const_0_0, save_12/RestoreV2_4/tensor_names, save_12/RestoreV2_4/shape_and_slices)]]
