In [ ]:
#svm可以用来分类 回归 离群值检测

In [1]:
from sklearn import svm

In [2]:
X = [[0,0],[1,1]]
y=[0,1]

In [3]:
clf = svm.SVC()

clf.fit(X , y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [4]:
clf.predict([[2,2]])

array([1])

In [5]:
clf.support_vectors_ #支持向量

array([[0., 0.],
       [1., 1.]])

In [6]:
clf.support_ #支持向量的索引下标

array([0, 1])

In [7]:
clf.n_support_ #每个类别的支持向量个数

array([1, 1])

In [ ]:
#SVC算法的多类别分类
#如果有k个类别 就构建k(k-1)/2个分类器

In [8]:
X = [[0],[1],[2],[3]]
Y = [0,1,2,3]

clf = svm.SVC(decision_function_shape='ovo')

In [9]:
clf.fit(X , Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
dec = clf.decision_function([[1]])

In [12]:
dec.shape #6=4*(4-1)/2

(1, 6)

In [13]:
clf.decision_function_shape ='ovr' #one vs rest
dec = clf.decision_function([[1]])
dec.shape

(1, 4)

In [ ]:
lin_clf = svm.LinearSVC() #使用的ovr方法

In [ ]:
#svm函数提供处理不平衡问题的参数
#class_weight给每个类别提供权重
#sample_weight给每个类别提供权重
#根据权重的不同 来处理数据不平衡

In [14]:
#===
#SVR
X = [[0,0],[2,2]]
y = [0.5 , 2.5]

clf = svm.SVR()
clf.fit(X, y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [15]:
clf.predict([[1,1]])

array([1.5])

In [ ]:
#===
#非监督的离群值的检测
svm.OneClassSVM()

In [17]:
#===
#使用自定义的核函数
import numpy as np

def my_kernel(X , Y):
    return np.dot(X , Y.T)

clf= svm.SVC(kernel=my_kernel)

In [18]:
#===
#也可以提前定义gram矩阵 参数kernel='precomputed'
X = np.array([[0,0],[1,1]])
y = [0,1]

clf = svm.SVC(kernel='precomputed')
gram = np.dot(X,X.T) #线性核
clf.fit(gram , y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto',
  kernel='precomputed', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [19]:
clf.predict(gram)

array([0, 1])