In [ ]:
# %USERPROFILE%/.keras/keras.json
# ~/.keras/keras.json

# 环境变量也可以 KERAS_BACKEND
# KERAS_BACKEND = tensorflow python -c 'from keras import backend;'
# Using TensorFlow backend

In [4]:
import numpy as np
from keras import backend as K

In [2]:
#tf.placeholder
input_ = K.placeholder(shape=(2,4,5))
input_ = K.placeholder(shape=(None , 4 , 5))
input_ = K.placeholder(ndim=3)

In [5]:
#tf.variable
val = np.random.random((3,4,5))
var = K.variable(value=val)

var = K.zeros(shape=(3,4,5))
var = K.ones(shape=(3,4,5))

In [ ]:
#只是使用 由keras的后端接口完成 不需要关心具体细节
a = b+c*K.abs(d)
c = K.dot(a , K.transpose(b))
a = K.sum(b , axis = 2)
a = K.softmax(b)
a = K.concatenate([b,c] , axis = -1)

In [6]:
K.backend()

'tensorflow'

In [7]:
K.epsilon()
#K.set_epsilon() #设置此值

1e-07

In [8]:
K.floatx()
#K.set_floatx()

'float32'

In [10]:
#将数据转化为keras的floatx类型
arr = np.array([1.0 , 2.0] , dtype='float64')
new_arr = K.cast_to_floatx(arr)
new_arr.dtype

dtype('float32')

In [11]:
K.image_data_format()
#K.set_image_data_format()

'channels_last'

In [14]:
x = K.placeholder(shape=(1,2))
K.is_keras_tensor(x)

False

In [15]:
np_var = np.array([1,2])
K.is_keras_tensor(np_var)

ValueError: Unexpectedly found an instance of type `<class 'numpy.ndarray'>`. Expected a symbolic tensor instance.

In [16]:
keras_var = K.variable(np_var)
K.is_keras_tensor(keras_var)

False

In [18]:
keras_placeholder = K.placeholder(shape=(2,4,5))
K.is_keras_tensor(keras_placeholder)

False

In [20]:
K.get_uid(prefix='ha')
#获取计算图的uid
# K.reset_uids()

1

In [ ]:
K.clear_session()
#结束当前tf计算图 新建一个

In [ ]:
K.manual_variable_initialization()
#用默认值初始化 还是用户手动初始化

In [21]:
K.learning_phase()
#K.set_learning_phase()
#模型执行在训练模式还是测试模式下

<tf.Tensor 'keras_learning_phase:0' shape=<unknown> dtype=bool>

In [24]:
#K.is_sparse()
#判断是否稀疏张量 由张量类型决定 不是实际有多稀疏
a = K.placeholder((2,2) , sparse=False)
K.is_sparse(a)

False

In [25]:
a = K.placeholder((2,2) , sparse=True)
K.is_sparse(a)

True

In [26]:
K.is_sparse(K.to_dense(a))
#转为不稀疏的张量

False

In [ ]:
K.variable()
K.placeholder()

In [27]:
tf_session = K.get_session()
val = K.variable([[1,2],[2,3],[4,5]])

K.shape(val) #返回一个张量的符号shape 就是返回值的类型是tensor

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [28]:
K.shape(val).eval(session = tf_session)

array([3, 2])

In [29]:
K.int_shape(val)

(3, 2)

In [31]:
K.ndim(val)
#返回张量的阶数

2

In [32]:
K.dtype(val)

'float32'

In [34]:
K.eval(val)

array([[1., 2.],
       [2., 3.],
       [4., 5.]], dtype=float32)

In [35]:
K.eval(K.zeros((2,4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [36]:
K.eval(K.ones((2,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [37]:
K.eval(K.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [ ]:
#生成与指定参数的张量相同的shape的全0 全1 张量
K.zeros_like()
K.ones_like()

In [ ]:
K.random_uniform_variable() #均匀分布

In [38]:
K.count_params(val)
#看下面的模块

6

In [39]:
val.shape

TensorShape([Dimension(3), Dimension(2)])

In [ ]:
K.cast()#改变张量数据类型

In [ ]:
K.update(x , new_x) #用new_x更新x

In [ ]:
K.update_add(x , increment)
K.update_sub(x , decrement)



In [ ]:
K.moving_average_update()

In [44]:
x = K.variable([[1,2,3] , [2,3,4]])
y = K.ones(shape=(4,3,5))

In [45]:
K.eval(y)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [49]:
K.eval(K.dot(x,y))
#张量乘积

array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]]], dtype=float32)

In [ ]:
K.batch_dot(x, y,axes=) #x y的shape的第一维为batch_size

In [ ]:
K.transpose()

In [ ]:
K.gather() #在给定的张量中检索给定下标的向量

In [ ]:
K.max()
K.min()
K.sum() #在给定轴上计算和
K.prod() #计算积 在给定轴上

K.cumsum() #给定轴上的累计和
K.cumprod() #给定轴上的累计积

In [53]:
val = K.variable([[1,2,3],[2,3,4]])
K.eval(K.sum(val , axis=0))

array([3., 5., 7.], dtype=float32)

In [54]:
K.eval(K.sum(val , axis=1))

array([6., 9.], dtype=float32)

In [55]:
K.eval(K.prod(val , axis=0))

array([ 2.,  6., 12.], dtype=float32)

In [56]:
K.eval(K.cumsum(val , axis=0))

array([[1., 2., 3.],
       [3., 5., 7.]], dtype=float32)

In [57]:
K.eval(K.cumsum(val , axis=1))

array([[1., 3., 6.],
       [2., 5., 9.]], dtype=float32)

In [58]:
K.eval(K.cumprod(val , axis=0))

array([[ 1.,  2.,  3.],
       [ 2.,  6., 12.]], dtype=float32)

In [59]:
K.eval(K.cumprod(val , axis=1))

array([[ 1.,  2.,  6.],
       [ 2.,  6., 24.]], dtype=float32)

In [ ]:
K.var()
K.std()
K.mean()

In [ ]:
K.any() #逻辑或
K.all() #逻辑与

K.argmin()
K.argmax()

K.square()
K.abs()
K.sqrt()
K.exp()
K.log()

K.logsumexp() #等于log(sum(exp())) 但是这个函数更加数值稳定

K.round() #四舍五入
K.sign() #符号函数

K.pow()
K.clip() #数值截断

K.equal()
K.not_equal()

K.greater() #x>y
K.greater_equal() #>=
K.less()
K.less_equal()

K.maximum() #element-wise取两个张量的最大值
K.minimum()

K.sin()
K.cos()

In [ ]:
K.normalize_batch_in_training() #一个batch中的数据先计算均值和方差 然后batch-norm
K.batch_normalization() #BatchNormalization layer

K.concatenate()
K.reshape()

K.permute_dimensions() #按照第二个参数重新排列张量

In [ ]:
K.resize_images() #对图片(2维物体缩放[还有一个channel])进行缩放 height width
K.resize_volumes() #(2维物体缩放[还有一个channel])depth height width channel


In [ ]:
K.repeat_elements() #将给定轴上的变量元素重复rep次

In [60]:
val = K.variable([[[1,2],[3,4]],
                  [[2,3],[1,2]]])

K.int_shape(val)

(2, 2, 2)

In [65]:
K.eval(K.repeat_elements(val , 2,axis=0))

array([[[1., 2.],
        [3., 4.]],

       [[1., 2.],
        [3., 4.]],

       [[2., 3.],
        [1., 2.]],

       [[2., 3.],
        [1., 2.]]], dtype=float32)

In [68]:
val = K.variable([[1,2],[3,4]])
K.eval(K.repeat(val,2))

array([[[1., 2.],
        [1., 2.]],

       [[3., 4.],
        [3., 4.]]], dtype=float32)

In [71]:
K.eval(K.arange(1 , stop=5 , step=0.3))
#K.arrange() #区间评分 插值

array([1.       , 1.3      , 1.5999999, 1.8999999, 2.1999998, 2.4999998,
       2.7999997, 3.0999997, 3.3999996, 3.6999996, 3.9999995, 4.2999997,
       4.6      , 4.9      ], dtype=float32)

In [73]:
val = K.variable([[1,2],[3,4]])
K.eval(K.tile(val,[1,2])) #在各个维度上重复n次 n必须等于第一个参数（张量）的阶数

array([[1., 2., 1., 2.],
       [3., 4., 3., 4.]], dtype=float32)

In [74]:
val = K.variable([[[1,2],[3,4]],
                  [[2,3],[1,2]]])

K.eval(K.batch_flatten(val))

array([[1., 2., 3., 4.],
       [2., 3., 1., 2.]], dtype=float32)

In [ ]:
K.expand_dims()

In [78]:
val = K.variable([[[1,2],[3,4]],
                  [[2,3],[1,2]]])

K.eval(K.squeeze(val )) #移除axis从张量中

TypeError: squeeze() missing 1 required positional argument: 'axis'

In [ ]:
K.temporal_padding() #向3d张量中间维度 左右两端填充padding个0
K.spatial_2d_padding()
K.spatial_3d_padding()

In [ ]:
K.stack()

K.one_hot()


In [79]:
import keras

In [ ]:
K.reverse()

In [ ]:
K.get_value() #以numpy array的形式返回张量的值
K.batch_get_value() #以numpy array list的形式返回多个张量的值

K.set_value()
K.batch_set_value()

In [ ]:
K.print_tensor()

K.function()

In [ ]:
K.gradients() #第一个参数关于第二个参数的梯度

K.stop_gradient()

K.rnn()

In [ ]:
K.switch() #根据第一个参数的真假来决定使用第二个还是第三个表达式

In [ ]:
K.in_train_phase() #训练模式 选择第一个参数 否则第二个参数
K.in_test_phase()

In [ ]:
K.relu()
K.elu()
K.softmax()
K.softplus()
K.softsign()
K.sigmoid()
K.hard_sigmoid()
K.tanh()
K.categorical_crossentropy()
K.sparse_categorical_crossentropy()
K.binary_crossentropy()

K.dropout()
K.l2_normalize()

#判断目标是否在predictions的前k大值位置
K.in_top_k()

In [ ]:
K.conv1d()
K.conv2d()

K.conv2d_transpose() #反卷积
K.conv3d()
K.conv3d_transpose()

K.pool2d()
K.pool3d()

K.bias_add()


In [ ]:
K.random_normal()
K.random_uniform()
K.random_binomial()
K.truncated_normal()

In [ ]:
#CTC 暂时未了解
K.ctc_label_dense_to_sparse()
K.ctc_batch_cost()
K.ctc_decode()

In [ ]:
K.map_fn() #将函数作用于变量的元素上

In [ ]:
K.foldl() #从左连接 fn：函数，例如：lambda acc, x: acc + x
K.foldr() #从右连接