In [ ]:
#最近邻可以处理监督和无监督
#无监督的最近邻是流形学习和光谱聚类的基础

In [1]:
#===
#最近邻算法中 数据的邻居
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [5]:
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
nbrs = NearestNeighbors(n_neighbors=1 , algorithm='ball_tree').fit(X)
distances , indices = nbrs.kneighbors(X)

In [6]:
indices

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

In [7]:
distances

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [8]:
#===
#KD tree
from sklearn.neighbors import KDTree
import numpy as np
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
kdt = KDTree(X , leaf_size = 30 , metric='euclidean')
kdt.query(X , k=2 , return_distance=False)

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]], dtype=int64)

In [ ]:
#===
#有两种分类器
#一种是KNN 一种是基于半径信息的
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import RadiusNeighborsClassifier

In [ ]:
#knn在进行分类时 可以为每一个投票加上权重 例如 投票权重与距离成反比

In [1]:
#===
#knn regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import RadiusNeighborsRegressor

In [2]:
#===
#nearest centroid classifier
from sklearn.neighbors.nearest_centroid import NearestCentroid
import numpy as np

X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
y = np.array([1,1,1,2,2,2])

clf = NearestCentroid()
clf.fit(X , y)

NearestCentroid(metric='euclidean', shrink_threshold=None)